version: '3.9'

services:
  reverse-proxy:
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: ./.docker/backend
      dockerfile: Dockerfile
      args:
        CLONE_REPO: git@github.com:loic-cariou/djangoRestStarter.git
        HOST_REPO: github.com
    depends_on:
      - postgres
    volumes:
      - api-data:/home/app/application
    labels:
      - "traefik.http.routers.owotcms.rule=Host(`api.localhost`)"
  
  front:
    build:
      context: ./.docker/frontend
      dockerfile: Dockerfile
      args:
        CLONE_REPO: git@github.com:loic-cariou/reactStarter.git
        HOST_REPO: github.com
    depends_on:
      - api
    volumes:
      - front-data:/home/app/application
    labels:
      - "traefik.http.routers.front.rule=Host(`front.localhost`)"

  postgres:
    build: ./.docker/postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    labels:
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"


volumes:
  postgres-data: {}
  api-data: {}
  front-data: {}
